### ISSUE TITLE
lb_context is passed to all methods

### ISSUE THREAD

**Issue by petreeftime** [intel-iot-devkit/littleb#2]
Are there any use cases where there would be multiple `lb_context`s used? I think `lb_init` should allocate a single `lb_context` and save it for any other method to use, instead of having it passed as a parameter every single time.

**Comment by arfoll** [comment]
This is a good point, it does seem like this is not really needed, we can be pretty sure of one instance of bluez running at the same time even if there may be multiple BLE adapters. @shiranbm does this make sense?

**Comment by Hbrinj** [comment]
Hi can you rebase the commit message to match the style we use please, thanks.

**Comment by petreeftime** [comment]
It should be done now. I had to merge with the new commits.

**Comment by Hbrinj** [comment]
Hey, I'm just currently away and will take a proper look next week, thanks for the pr.

**Comment by Hbrinj** [comment]
fixed in commit 7c0cead1c2c365a8bfdbcadf0d90db3bb7fc432f
